name: "🚀 Feature Request"
description: Suggest a new feature for Zopio
title: "[Feature]: "
labels: ["feature request", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!  
        Your ideas help make Zopio better for everyone.  
        Please check existing [issues](https://github.com/zopiolabs/zopio/issues) and [discussions](https://github.com/zopiolabs/zopio/discussions) to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem context.
      placeholder: "I'm always frustrated when... / It would be great if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: "I would like Zopio to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or approaches you’ve considered.
      placeholder: "Other ways this could be solved include..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: "This feature would help when..."
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: Who would benefit from this feature?
      options:
        - Individual developers
        - Small teams
        - Large organizations
        - The entire community
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: affected-area
    attributes:
      label: Affected Modules/Packages
      description: Which parts of the Zopio codebase would this feature affect?
      options:
        - label: Core
        - label: API
        - label: UI
        - label: Infra / CI
        - label: Docs
        - label: Product Logic
        - label: Other / Not Sure

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have thoughts on how this could be implemented, share them here.
      placeholder: "This could be implemented by..."

  - type: textarea
    id: related-links
    attributes:
      label: Related Issues / Discussions
      description: Link to any related issues, discussions, or external resources.
      placeholder: "e.g., #123, Discussion link, RFC doc..."

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Changes
      options:
        - label: This feature might require breaking changes
        - label: This feature can be implemented without breaking changes
        - label: I'm not sure about breaking changes

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I would need guidance on implementation
        - label: I can help with design/specification
        - label: I can help test the implementation

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/zopiolabs/zopio/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
