# Reusable Workflow: Node.js Setup
#
# Purpose: Centralized Node.js and pnpm setup to reduce duplication
#          across workflows. No caching as per requirements.
#
# Usage:
#   jobs:
#     example:
#       uses: ./.github/workflows/setup-node.yml
#       with:
#         node-version: '20'
#         pnpm-version: '10.11.0'

name: Setup Node.js Environment

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        type: string
        default: '20'
      pnpm-version:
        description: 'pnpm version to use'
        type: string
        default: '10.11.0'
      install-deps:
        description: 'Whether to install dependencies'
        type: boolean
        default: true
      frozen-lockfile:
        description: 'Use frozen lockfile for dependencies'
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        if: inputs.install-deps
        run: |
          if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi